const types = {
  IS_TYPING: 'IS_TYPING',
  IS_END_OF_CONVERSATION: 'IS_END_OF_CONVERSATION',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  CLOSE_CONVERSATION: 'CLOSE_CONVERSATION',
  SENT_MESSAGE: 'SENT_MESSAGE',
  CONVERSATION_LOADED: 'CONVERSATION_LOADED',
  IS_ERROR: 'IS_ERROR',
  IS_SOCKET_ERROR: 'IS_SOCKET_ERROR',
  EXERCISES_LOADED: 'EXERCISES_LOADED',
};

export default types;
